--
-------------------------------------------------------------------------------------------
-- Copyright © 2010-2013, Xilinx, Inc.
-- This file contains confidential and proprietary information of Xilinx, Inc. and is
-- protected under U.S. and international copyright and other intellectual property laws.
-------------------------------------------------------------------------------------------
--
-- Disclaimer:
-- This disclaimer is not a license and does not grant any rights to the materials
-- distributed herewith. Except as otherwise provided in a valid license issued to
-- you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
-- MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
-- DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
-- INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
-- OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
-- (whether in contract or tort, including negligence, or under any other theory
-- of liability) for any loss or damage of any kind or nature related to, arising
-- under or in connection with these materials, including for any direct, or any
-- indirect, special, incidental, or consequential loss or damage (including loss
-- of data, profits, goodwill, or any type of loss or damage suffered as a result
-- of any action brought by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the possibility of the same.
--
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-safe, or for use in any
-- application requiring fail-safe performance, such as life-support or safety
-- devices or systems, Class III medical devices, nuclear facilities, applications
-- related to the deployment of airbags, or any other applications that could lead
-- to death, personal injury, or severe property or environmental damage
-- (individually and collectively, "Critical Applications"). Customer assumes the
-- sole risk and liability of any use of Xilinx products in Critical Applications,
-- subject only to applicable laws and regulations governing limitations on product
-- liability.
--
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
--
-------------------------------------------------------------------------------------------
--
--
-- Production definition of a 1K program for KCPSM6 in a Virtex-6 device using a 
-- RAMB18E1 primitive.
--
-- Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
--       expansion with minimum changes being required to the hardware description. 
--       Only the lower 10-bits of the address are actually used for the 1K address range
--       000 to 3FF hex.  
--
-- Program defined by 'C:\TES_project\fpga_ise\controllerlib\PSM\IO_controller_program.psm'.
--
-- Generated by KCPSM6 Assembler: 11 Feb 2016 - 12:55:37. 
--
-- Assembler used ROM_form template: ROM_form_V6_1K_14March13.vhd
--
--
-- Standard IEEE libraries
--
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
--
-- The Unisim Library is used to define Xilinx primitives. It is also used during
-- simulation. The source can be viewed at %XILINX%\vhdl\src\unisims\unisim_VCOMP.vhd
--  
library unisim;
use unisim.vcomponents.all;
--
--
entity IO_controller_program is
    Port (      address : in std_logic_vector(11 downto 0);
            instruction : out std_logic_vector(17 downto 0);
                 enable : in std_logic;
                    clk : in std_logic);
    end IO_controller_program;
--
architecture low_level_definition of IO_controller_program is
--
signal  address_a : std_logic_vector(13 downto 0);
signal  data_in_a : std_logic_vector(17 downto 0);
signal data_out_a : std_logic_vector(17 downto 0);
signal  address_b : std_logic_vector(13 downto 0);
signal  data_in_b : std_logic_vector(17 downto 0);
signal data_out_b : std_logic_vector(17 downto 0);
signal   enable_b : std_logic;
signal      clk_b : std_logic;
signal       we_b : std_logic_vector(3 downto 0);
--
begin
--
  address_a <= address(9 downto 0) & "1111";
  instruction <= data_out_a(17 downto 0);
  data_in_a <= "0000000000000000" & address(11 downto 10);
  --
  address_b <= "11111111111111";
  data_in_b <= data_out_b(17 downto 0);
  enable_b <= '0';
  we_b <= "0000";
  clk_b <= '0';
  --
  --
  -- 
  kcpsm6_rom: RAMB18E1
  generic map ( READ_WIDTH_A => 18,
                WRITE_WIDTH_A => 18,
                DOA_REG => 0,
                INIT_A => "000000000000000000",
                RSTREG_PRIORITY_A => "REGCE",
                SRVAL_A => X"000000000000000000",
                WRITE_MODE_A => "WRITE_FIRST",
                READ_WIDTH_B => 18,
                WRITE_WIDTH_B => 18,
                DOB_REG => 0,
                INIT_B => X"000000000000000000",
                RSTREG_PRIORITY_B => "REGCE",
                SRVAL_B => X"000000000000000000",
                WRITE_MODE_B => "WRITE_FIRST",
                INIT_FILE => "NONE",
                SIM_COLLISION_CHECK => "ALL",
                RAM_MODE => "TDP",
                RDADDR_COLLISION_HWCONFIG => "DELAYED_WRITE",
                SIM_DEVICE => "VIRTEX6",
                INIT_00 => X"F10291014106F103410E410E410E410E31F04180200300EF0054002717030039",
                INIT_01 => X"201C910140062020D1001001310F4180F0042012910140062017D1001001B103",
                INIT_02 => X"4F061F1000EA20D10E000021BD03BC0100EA50003007400E400E400E9080F001",
                INIT_03 => X"9080000601DF02360006B0C402A620D1370F1C371D0C1E0B5F024F064F064F06",
                INIT_04 => X"91016052D004908011FF5000D5016046D00290805000B00402A6B084203FD040",
                INIT_05 => X"206D1401E06002C602C0206FD50D2057004B1400160000E550009501204C1000",
                INIT_06 => X"D702205716014750606190014F004E004D004C004B004A004900480047061004",
                INIT_07 => X"6086D7C02086D70F5780207CD40057402079D61217002076D7032076D7012076",
                INIT_08 => X"B021009EB01150000093009EB0115000460F00E0500036002083B0F46084D703",
                INIT_09 => X"D908DA10DB205000DC04DD08DE10DF2050009C049D089E109F205000B0820098",
                INIT_0A => X"D200500020B3A0AF00C1009012100210500020AAA0A800C100A012005000D804",
                INIT_0B => X"32FF60BBD20050004180021060BFD200500020BDA0B800C100801208021060BF",
                INIT_0C => X"5720370F20E0573050004080E0C6500030FF1100E0C220C94006910111085000",
                INIT_0D => X"02AF04C002AF04D002AF04E002AF04F060E0D4F0047020E0D401340F047020E0",
                INIT_0E => X"B30250001C001D001E001F001700180019001A001B0050000046150D02AF0470",
                INIT_0F => X"22D2D70220CC2220A15BC900B00420CCD90060CCCB30130120FEA101CB301301",
                INIT_10 => X"04D002AF04E002AF04F0B401D34044303400133D140103B0E0CCCB10B10122DB",
                INIT_11 => X"00EA0046150D02AF047002AF048002AF049002AF04A002AF04B002AF04C002AF",
                INIT_12 => X"4F004E004D004C004706100421331401E12A02C62135D50D2122004B14001600",
                INIT_13 => X"13041302130120E0572037CF20D1D60A20D1D602B201212216014750612B9001",
                INIT_14 => X"50006146910101504200C3409302D00230800020110813801340132013101308",
                INIT_15 => X"D8412166D70260CC02145000D08010005000D00200000000000030FED0025001",
                INIT_16 => X"0280049020E0016E0181D98020D1016E0186D980216A60CEDC60616AD83F20CE",
                INIT_17 => X"617791014200C34093020150D002308000201108500001580C20017602C00176",
                INIT_18 => X"008D1C0006C020D1008D50000176120101761200500001761200017612005000",
                INIT_19 => X"440E440E01A9D0801004440E440E01A9D0801002440E440E01A9D08010010460",
                INIT_1A => X"018121CD21C7D401E1B521BBD40320D102A6008D0C600296015801A9D0801008",
                INIT_1B => X"017612210176123F018150000176120801761240018150000176120C01761240",
                INIT_1C => X"01761240018150000176120E0176124001815000017612200176123F01815000",
                INIT_1D => X"B00450000176120901761240018150000176120A01761240018150000176120D",
                INIT_1E => X"12201200120021E63500140101761000D2FF454014ED15010181D08010009001",
                INIT_1F => X"12531200125212001251124612501200124412801241120812401220123F1200",
                INIT_20 => X"12751200126A1200126812001266120012631200126212001257120012551200",
                INIT_21 => X"2216350014021000C28050004207621BD2FF454014ED150112FF120012761200",
                INIT_22 => X"02800145D980049020E0022C120020D1022C128000EA20CE2229D7012225D702",
                INIT_23 => X"F200500001501000623FD2FF4540144D1502B60450000C200158014502C00145",
                INIT_24 => X"123D120C123C223935001401015801454540350014010145B20001451200D680",
                INIT_25 => X"12491221124812031243120212421202124112031240120C123F120C123E120C",
                INIT_26 => X"1251122112501200124F1221124E1200124D1221124C1200124B1221124A1200",
                INIT_27 => X"1205120512041200125712211256120012551221125412001253122112521200",
                INIT_28 => X"125A12021245120A120C1200120B1210120A12701209126F1208120F12061200",
                INIT_29 => X"116B12EE22AA10B411C4120422AA1009113D120022AA10041100120012FF1201",
                INIT_2A => X"0540500062AAB200B100900122AA10E21104120022AA10941135127722AA1028",
                INIT_2B => X"5000153A1507A2BE950A5000004602BB350F0540004602BB450E450E450E450E",
                INIT_2C => X"500095F690001507E2D09511900095E9900015B9500035DFD000D57B9000D561",
                INIT_2D => X"E0CCD210E0CC20CE00A220D100896027D801E0CCD210E0CC202D00A25000150A",
                INIT_2E => X"000000000000000000000000000000000000000020D1008D218BD20560CED803",
                INIT_2F => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_30 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_31 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_32 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_33 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_34 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_35 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_36 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_37 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_38 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_39 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3A => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3B => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3C => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3D => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3E => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3F => X"0000000000000000000000000000000000000000000000000000000000000000",
               INITP_00 => X"CC34D37764D555549EB7828B702B0AAC2AAA00154A20A1529741A5D096551BA2",
               INITP_01 => X"DBD375F5200002888888C342089E0F52364DBE136F84BE0AAAAA802AAAAA68AD",
               INITP_02 => X"D4280A220AAAAB3777A8A008B64202AAAA0DDA4D5549EDE0A2222222222A50D2",
               INITP_03 => X"AAAAAAAAAA5B60AD288A88A88A88A88A88A88A88ACF2A2A85A1685A082A88A22",
               INITP_04 => X"AAAAAAAAAAAAAAAAAAAAAAAAAA5A9622A8D808A228A28ADD976760AAAAAAAAAA",
               INITP_05 => X"0000000000000ADCDFAB37E99DDDD8DD976A0A552D5808080808080AAAAAAAAA",
               INITP_06 => X"0000000000000000000000000000000000000000000000000000000000000000",
               INITP_07 => X"0000000000000000000000000000000000000000000000000000000000000000")
  port map(   ADDRARDADDR => address_a,
                  ENARDEN => enable,
                CLKARDCLK => clk,
                    DOADO => data_out_a(15 downto 0),
                  DOPADOP => data_out_a(17 downto 16), 
                    DIADI => data_in_a(15 downto 0),
                  DIPADIP => data_in_a(17 downto 16), 
                      WEA => "00",
              REGCEAREGCE => '0',
            RSTRAMARSTRAM => '0',
            RSTREGARSTREG => '0',
              ADDRBWRADDR => address_b,
                  ENBWREN => enable_b,
                CLKBWRCLK => clk_b,
                    DOBDO => data_out_b(15 downto 0),
                  DOPBDOP => data_out_b(17 downto 16), 
                    DIBDI => data_in_b(15 downto 0),
                  DIPBDIP => data_in_b(17 downto 16), 
                    WEBWE => we_b,
                   REGCEB => '0',
                  RSTRAMB => '0',
                  RSTREGB => '0');
--
--
end low_level_definition;
--
------------------------------------------------------------------------------------
--
-- END OF FILE IO_controller_program.vhd
--
------------------------------------------------------------------------------------
