--
-------------------------------------------------------------------------------------------
-- Copyright © 2010-2013, Xilinx, Inc.
-- This file contains confidential and proprietary information of Xilinx, Inc. and is
-- protected under U.S. and international copyright and other intellectual property laws.
-------------------------------------------------------------------------------------------
--
-- Disclaimer:
-- This disclaimer is not a license and does not grant any rights to the materials
-- distributed herewith. Except as otherwise provided in a valid license issued to
-- you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
-- MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
-- DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
-- INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
-- OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
-- (whether in contract or tort, including negligence, or under any other theory
-- of liability) for any loss or damage of any kind or nature related to, arising
-- under or in connection with these materials, including for any direct, or any
-- indirect, special, incidental, or consequential loss or damage (including loss
-- of data, profits, goodwill, or any type of loss or damage suffered as a result
-- of any action brought by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the possibility of the same.
--
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-safe, or for use in any
-- application requiring fail-safe performance, such as life-support or safety
-- devices or systems, Class III medical devices, nuclear facilities, applications
-- related to the deployment of airbags, or any other applications that could lead
-- to death, personal injury, or severe property or environmental damage
-- (individually and collectively, "Critical Applications"). Customer assumes the
-- sole risk and liability of any use of Xilinx products in Critical Applications,
-- subject only to applicable laws and regulations governing limitations on product
-- liability.
--
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
--
-------------------------------------------------------------------------------------------
--
--
-- Production definition of a 1K program for KCPSM6 in a Virtex-6 device using a 
-- RAMB18E1 primitive.
--
-- Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
--       expansion with minimum changes being required to the hardware description. 
--       Only the lower 10-bits of the address are actually used for the 1K address range
--       000 to 3FF hex.  
--
-- Program defined by 'C:\TES_project\fpga_ise\teslib\PSM\IO_controller_program.psm'.
--
-- Generated by KCPSM6 Assembler: 23 Jul 2016 - 11:54:36. 
--
-- Assembler used ROM_form template: ROM_form_V6_1K_14March13.vhd
--
--
-- Standard IEEE libraries
--
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
--
-- The Unisim Library is used to define Xilinx primitives. It is also used during
-- simulation. The source can be viewed at %XILINX%\vhdl\src\unisims\unisim_VCOMP.vhd
--  
library unisim;
use unisim.vcomponents.all;
--
--
entity IO_controller_program is
    Port (      address : in std_logic_vector(11 downto 0);
            instruction : out std_logic_vector(17 downto 0);
                 enable : in std_logic;
                    clk : in std_logic);
    end IO_controller_program;
--
architecture low_level_definition of IO_controller_program is
--
signal  address_a : std_logic_vector(13 downto 0);
signal  data_in_a : std_logic_vector(17 downto 0);
signal data_out_a : std_logic_vector(17 downto 0);
signal  address_b : std_logic_vector(13 downto 0);
signal  data_in_b : std_logic_vector(17 downto 0);
signal data_out_b : std_logic_vector(17 downto 0);
signal   enable_b : std_logic;
signal      clk_b : std_logic;
signal       we_b : std_logic_vector(3 downto 0);
--
begin
--
  address_a <= address(9 downto 0) & "1111";
  instruction <= data_out_a(17 downto 0);
  data_in_a <= "0000000000000000" & address(11 downto 10);
  --
  address_b <= "11111111111111";
  data_in_b <= data_out_b(17 downto 0);
  enable_b <= '0';
  we_b <= "0000";
  clk_b <= '0';
  --
  --
  -- 
  kcpsm6_rom: RAMB18E1
  generic map ( READ_WIDTH_A => 18,
                WRITE_WIDTH_A => 18,
                DOA_REG => 0,
                INIT_A => "000000000000000000",
                RSTREG_PRIORITY_A => "REGCE",
                SRVAL_A => X"000000000000000000",
                WRITE_MODE_A => "WRITE_FIRST",
                READ_WIDTH_B => 18,
                WRITE_WIDTH_B => 18,
                DOB_REG => 0,
                INIT_B => X"000000000000000000",
                RSTREG_PRIORITY_B => "REGCE",
                SRVAL_B => X"000000000000000000",
                WRITE_MODE_B => "WRITE_FIRST",
                INIT_FILE => "NONE",
                SIM_COLLISION_CHECK => "ALL",
                RAM_MODE => "TDP",
                RDADDR_COLLISION_HWCONFIG => "DELAYED_WRITE",
                SIM_DEVICE => "VIRTEX6",
                INIT_00 => X"600DD0029080209B0E000253BD03BC0100B0200400C1001B0007170302380292",
                INIT_01 => X"201E00121400160000AB500095012013100091016019D004908011FF5000D501",
                INIT_02 => X"4E004D004C004B004A00490048004706100420341401E027022C02262036D50A",
                INIT_03 => X"57402040D6121700203DD703203DD701203DD702201E16014750602890014F00",
                INIT_04 => X"5000460F00A650003600204AB0F4604BD703604DD7C0204DD70F57802043D400",
                INIT_05 => X"9D089E109F205000005D0000B0820062B0210068B0115000005D00000068B011",
                INIT_06 => X"A072008B00A012005000D804D908DA10DB205000DC04DD08DE10DF2050009C04",
                INIT_07 => X"A082008B0080120802106089D2005000207DA079008B00901210021050002074",
                INIT_08 => X"E08C2093400691011108500032FF6085D2005000418002106089D20050002087",
                INIT_09 => X"021504F060A6D4F0047020A65720370F20A6573050004080E090500030FF1100",
                INIT_0A => X"1700180019001A001B005000000D150A02150470021504C0021504D0021504E0",
                INIT_0B => X"370F1C361D0B1E175F074F064F064F064F061F1000B050001C001D001E001F00",
                INIT_0C => X"209621E2A171C900B0042096D90020D3E096CB30B30120C9DB2020D0DB10209B",
                INIT_0D => X"021504D0021504E0021504F0B401D2404430340003B0130C140122642259D702",
                INIT_0E => X"160000B0000D150A021504700215048002150490021504A0021504B0021504C0",
                INIT_0F => X"90014F004E004D004C004706100421021401E0F9022C2104D50A20F100121400",
                INIT_10 => X"120812041202120120A6572037CF209BD60A209BD602B20120F11601475060FA",
                INIT_11 => X"91014200C3409302D00230FED0025001D0023080002011081280124012201210",
                INIT_12 => X"0135028004905000D08010005000D00200000000000030FED002500150006115",
                INIT_13 => X"5000613691014200C34093020122D0023080002011085000012A0C20013502C0",
                INIT_14 => X"1221123F12001220128012005000013512010135120050000135120001351200",
                INIT_15 => X"1200125512001253120012521200125112461250120012441280124112081240",
                INIT_16 => X"12001276120012751200126A1200126812001266120012631200126212001257",
                INIT_17 => X"209B012D0145D98021806098DC606180D83F2098D841217CD702609601D612FF",
                INIT_18 => X"D0801002440E440E01A0D0801001046000551C0006C0005520A6012D0140D980",
                INIT_19 => X"209B00550C6001FC012A01A0D0801008440E440E01A0D0801004440E440E01A0",
                INIT_1A => X"120801351240014050000135120C01351240014021C421BED401E1B821B2D403",
                INIT_1B => X"124001405000013512200135123F01405000013512210135123F014050000135",
                INIT_1C => X"50000135120A01351240014050000135120D01351240014050000135120E0135",
                INIT_1D => X"14021000C2805000420761DDD2FF4540144A1501500001351209013512400140",
                INIT_1E => X"D980049020A601EE1200209B01EE128000B0209821EBD70121E7D70221D83500",
                INIT_1F => X"22101009113D1200221010011100120050000C20012A011402C0011402800114",
                INIT_20 => X"221010E211041200221010941135127722101028116B12EE221010B411C41204",
                INIT_21 => X"000D0221350F0540000D0221450E450E450E450E054050006210B200B1009001",
                INIT_22 => X"900095E9900015B9500035DFD000D57B9000D5615000153A1507A224950A5000",
                INIT_23 => X"4106F103410E410E410E410E31F041805000150A500095F690001507E2369511",
                INIT_24 => X"40062252D1001001310F4180F0042244910140062249D1001001B103F1029101",
                INIT_25 => X"2098D2012096D203E09620B502875000301F400E400E400E9080F001224E9101",
                INIT_26 => X"1201209B00556184D8802098D2022096D203E09620980287209B00506007DA80",
                INIT_27 => X"1200120012001202120212001203120312031203120312031203120312031203",
                INIT_28 => X"5401454035000420146F15021000D000006C1201120012001200120012001200",
                INIT_29 => X"B004020C020CB084020C2295D040908002FD02A10238B0C401F8B0E450004480",
                INIT_2A => X"0114B20001141200D680F20050000122100062AAD2FF454014B81502B6045000",
                INIT_2B => X"120C123F120C123E120C123D120C123C22A435001401012A0114454035001401",
                INIT_2C => X"1200124B1221124A120012491221124812031243120212421202124112031240",
                INIT_2D => X"120012531221125212001251122112501200124F1221124E1200124D1221124C",
                INIT_2E => X"126F1208120F1206120012051205120412001257122112561200125512211254",
                INIT_2F => X"10009001B00412FF1201125A12021245120A120C1200120B1210120A12701209",
                INIT_30 => X"0000000000000000000023043500140101351000D2FF4540144A15010140D080",
                INIT_31 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_32 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_33 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_34 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_35 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_36 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_37 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_38 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_39 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3A => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3B => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3C => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3D => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3E => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3F => X"0000000000000000000000000000000000000000000000000000000000000000",
               INITP_00 => X"E136F84BE0AAAAA8028AAA8A9A2B730D34DDD935555527ADE0A2DC0AC220AE8A",
               INITP_01 => X"55527B7828888888888A942DBD36D37600154A00002888888C2089E0F52364DB",
               INITP_02 => X"AAB3777AAAAAAAAAAAAAAAAAAAAA2288B50A0288828A008B508880AAAA837693",
               INITP_03 => X"80808A228A28ADD976760A22A22A22A22A22A22A22A22B3CA2A85A1685A082AA",
               INITP_04 => X"AAAAAAAAAB333EACCCFA1529741A5D09655199DDDD8DD976A0A552D580808080",
               INITP_05 => X"D2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA96A588AA3602AAB0AAA9250FAAAA",
               INITP_06 => X"000000000000000000000000000000000000000000000000000000000025B60A",
               INITP_07 => X"0000000000000000000000000000000000000000000000000000000000000000")
  port map(   ADDRARDADDR => address_a,
                  ENARDEN => enable,
                CLKARDCLK => clk,
                    DOADO => data_out_a(15 downto 0),
                  DOPADOP => data_out_a(17 downto 16), 
                    DIADI => data_in_a(15 downto 0),
                  DIPADIP => data_in_a(17 downto 16), 
                      WEA => "00",
              REGCEAREGCE => '0',
            RSTRAMARSTRAM => '0',
            RSTREGARSTREG => '0',
              ADDRBWRADDR => address_b,
                  ENBWREN => enable_b,
                CLKBWRCLK => clk_b,
                    DOBDO => data_out_b(15 downto 0),
                  DOPBDOP => data_out_b(17 downto 16), 
                    DIBDI => data_in_b(15 downto 0),
                  DIPBDIP => data_in_b(17 downto 16), 
                    WEBWE => we_b,
                   REGCEB => '0',
                  RSTRAMB => '0',
                  RSTREGB => '0');
--
--
end low_level_definition;
--
------------------------------------------------------------------------------------
--
-- END OF FILE IO_controller_program.vhd
--
------------------------------------------------------------------------------------
